import { SubscriptionModalProvider } from "@/lib/context/SubscriptionModalContext";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <SubscriptionModalProvider>{children}</SubscriptionModalProvider>;
}
