import { StripeProductData } from "@/lib/stripe/types/StripeProductData";
import { StripePriceData } from "@/lib/stripe/types/StripePriceData";

export const mockStripePrices: StripePriceData[] = [
  {
    id: "price_basic",
    active: true,
    billing_scheme: "per_unit",
    currency: "usd",
    description: "Basic plan price",
    interval: "month",
    interval_count: 1,
    metadata: {},
    recurring: {
      aggregate_usage: null,
      interval: "month",
      interval_count: 1,
      usage_type: "licensed",
      trial_period_days: null,
    },
    tax_behavior: "unspecified",
    tiers_mode: null,
    transform_quantity: null,
    type: "recurring",
    unit_amount: 1000,
    unit_amount_decimal: "1000",
    formatted_price: "$10",
    trial_period_days: null,
  },
  {
    id: "price_premium",
    active: true,
    billing_scheme: "per_unit",
    currency: "usd",
    description: "Premium plan price",
    interval: "month",
    interval_count: 1,
    metadata: {},
    recurring: {
      aggregate_usage: null,
      interval: "month",
      interval_count: 1,
      usage_type: "licensed",
      trial_period_days: null,
    },
    tax_behavior: "unspecified",
    tiers_mode: null,
    transform_quantity: null,
    type: "recurring",
    unit_amount: 2000,
    unit_amount_decimal: "2000",
    formatted_price: "$20",
    trial_period_days: null,
  },
];

export const mockStripeProducts: StripeProductData[] = [
  {
    id: "prod_basic",
    name: "Basic Plan",
    active: true,
    description: "Basic plan description",
    images: [],
    metadata: {
      firebaseRole: "basic",
      popular: "false",
      buttonText: "Subscribe to Basic",
    },
    price: mockStripePrices[0],
    object: "product",
    shippable: false,
    statement_descriptor: null,
    unit_label: null,
    created: 1234567890,
    updated: 1234567890,
    package_dimensions: null,
    role: "basic",
    tax_code: null,
    url: null,
  },
  {
    id: "prod_premium",
    name: "Premium Plan",
    active: true,
    description: "Premium plan description",
    images: [],
    metadata: {
      firebaseRole: "premium",
      popular: "true",
      buttonText: "Subscribe to Premium",
    },
    price: mockStripePrices[1],
    object: "product",
    shippable: false,
    statement_descriptor: null,
    unit_label: null,
    created: 1234567890,
    updated: 1234567890,
    package_dimensions: null,
    role: "premium",
    tax_code: null,
    url: null,
  },
];
